api:
  path: /api
  controller: App\Controller\ApiController::api

login_check:
  path:     /login_check
  methods:  [POST]

register:
  path: /register
  controller: App\Controller\ApiController::register
  methods: POST
